apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp10
  template:
    metadata:
      labels:
        app: webapp10
    spec:
      containers:
      - name: webapp10
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 8080
